#!/usr/local/bin/python3
'''
Problem 2 : Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
https://projecteuler.net/problem=2
---
프로그래머 Programmer : 제이스 Jace (https://jacealan.github.io)
사용언어 Language : 파이썬 Python 3.6.4
OS : macOS High Sierra 10.13.3
에디터 Editor : Visual Studio Code
'''


def solution():
    '''피보나치 수열'''

    fibonacci = [1, 2]
    while fibonacci[-1] <= 4000000:  # 수열 마지막값이 4000000 넘지 않도록
        fibonacci.append(fibonacci[-2] + fibonacci[-1])
    fibonacci.pop()  # 4000000이 넘는 마지막값 제거
    even_value = [x for x in fibonacci if x % 2 == 0]
    print(fibonacci)
    print(even_value)
    print('답은', sum(even_value))


if __name__ == '__main__':
    solution()
